model:
 name: RandomForestClassifier
 params:
  n_estimators: 100
  max_depth: 20
  min_samples_split: 5
  min_samples_leaf: 2
  max_features: sqrt
  random_state: 42
TF_IDF:
 params:
  ngram_range: [1,2]
  min_df: 5
  max_df: 0.85
  sublinear_tf: True